"""Add ban_reason to users

Revision ID: 43a0d99da89c
Revises: 76d8e6a1929f
Create Date: 2025-10-07 17:53:43.944619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a0d99da89c'
down_revision: Union[str, Sequence[str], None] = '76d8e6a1929f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ban_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ban_reason')
    # ### end Alembic commands ###
