"""Add notes table

Revision ID: 5369b0a7bf5e
Revises: 43a0d99da89c
Create Date: 2025-10-11 09:13:19.194960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5369b0a7bf5e'
down_revision: Union[str, Sequence[str], None] = '43a0d99da89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_notes_group_id'), 'notes', ['group_id'], unique=False)
    op.create_index(op.f('ix_notes_note_id'), 'notes', ['note_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_note_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_group_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
