"""add subjects table and relation to notes

Revision ID: 5fa884fa92d4
Revises: 431bf41acd85
Create Date: 2025-10-20 16:36:11.384083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa884fa92d4'
down_revision: Union[str, Sequence[str], None] = '431bf41acd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subjects_subject_id'), 'subjects', ['subject_id'], unique=False)
    op.add_column('notes', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notes_subject_id'), 'notes', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'notes', 'subjects', ['subject_id'], ['subject_id'], ondelete='SET NULL')
    op.drop_column('notes', 'subject')
    op.drop_column('users', 'university')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('university', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_notes_subject_id'), table_name='notes')
    op.drop_column('notes', 'subject_id')
    op.drop_index(op.f('ix_subjects_subject_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
