"""Add note_comments table

Revision ID: 75d22fe11587
Revises: 9c1e5f0aa712
Create Date: 2025-10-11 11:18:28.347487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d22fe11587'
down_revision: Union[str, Sequence[str], None] = '9c1e5f0aa712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_note_comments_comment_id'), 'note_comments', ['comment_id'], unique=False)
    op.create_index(op.f('ix_note_comments_note_id'), 'note_comments', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_comments_user_id'), 'note_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_comments_user_id'), table_name='note_comments')
    op.drop_index(op.f('ix_note_comments_note_id'), table_name='note_comments')
    op.drop_index(op.f('ix_note_comments_comment_id'), table_name='note_comments')
    op.drop_table('note_comments')
    # ### end Alembic commands ###
