"""Add notes_rating and saved_notes tables

Revision ID: 9c1e5f0aa712
Revises: 5369b0a7bf5e
Create Date: 2025-10-11 09:18:57.893034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1e5f0aa712'
down_revision: Union[str, Sequence[str], None] = '5369b0a7bf5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_ratings',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('rated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'user_id'),
    sa.UniqueConstraint('note_id', 'user_id', name='uq_note_user_rating')
    )
    op.create_index(op.f('ix_note_ratings_note_id'), 'note_ratings', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_ratings_user_id'), 'note_ratings', ['user_id'], unique=False)
    op.create_table('saved_notes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'note_id'),
    sa.UniqueConstraint('user_id', 'note_id', name='uq_user_saved_note')
    )
    op.create_index(op.f('ix_saved_notes_note_id'), 'saved_notes', ['note_id'], unique=False)
    op.create_index(op.f('ix_saved_notes_user_id'), 'saved_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_notes_user_id'), table_name='saved_notes')
    op.drop_index(op.f('ix_saved_notes_note_id'), table_name='saved_notes')
    op.drop_table('saved_notes')
    op.drop_index(op.f('ix_note_ratings_user_id'), table_name='note_ratings')
    op.drop_index(op.f('ix_note_ratings_note_id'), table_name='note_ratings')
    op.drop_table('note_ratings')
    # ### end Alembic commands ###
