"""notes table changes | remove groups

Revision ID: dbbcfaa3e48f
Revises: 75d22fe11587
Create Date: 2025-10-11 12:25:29.663955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbbcfaa3e48f'
down_revision: Union[str, Sequence[str], None] = '75d22fe11587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_group_id'), table_name='notes')
    op.drop_column('notes', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_notes_group_id'), 'notes', ['group_id'], unique=False)
    # ### end Alembic commands ###
